/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  user: {
    CreateUser: () => import('#controllers/user/controllers/create_user_controller'),
    DeleteUser: () => import('#controllers/user/controllers/delete_user_controller'),
    ListUsers: () => import('#controllers/user/controllers/list_users_controller'),
    ShowUser: () => import('#controllers/user/controllers/show_user_controller'),
    UpdateUser: () => import('#controllers/user/controllers/update_user_controller'),
  },
}
