/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type UserUserTransformer from '#transformers/user/user_transformer'

export namespace Data {
  export namespace User {
    export type User = InferData<UserUserTransformer>
    export namespace User {
      export type Variants = InferVariants<UserUserTransformer>
    }
  }
}
